READMEにpyxelのコードを追加
saitoxu/pyxel-breakout pull request #1
Opened 2024-01-15 11:52 UTC by funfunfunnofun

READMEの内容を変更

2024-01-15 11:55 UTC, saitoxu requested changes

2024-01-15 11:55 UTC, saitoxu commented on README.md
> +```sh
`# pyxel-atari-breakout`との間に改行を入れてほしいです。

2024-01-16 11:45 UTC, saitoxu commented on README.md
> +$ pyxel run atari_breakout/app.py
ディレクトリ名も変えたので以下のように修正をお願いします。

```suggestion
$ pyxel run breakout/app.py
```

2024-01-16 12:10 UTC, funfunfunnofun commented on README.md
> +```sh
対応しました！

2024-01-16 12:10 UTC, funfunfunnofun commented on README.md
> +$ pyxel run atari_breakout/app.py
対応しました！

2024-01-16 12:25 UTC, saitoxu approved these changes

2024-01-16 12:25 UTC, merged